### ISSUE TITLE
Local pins do not seem to be installed correctly. 

### ISSUE THREAD

**Issue by jordwalke** [whitequark/ocaml-m17n#1]
When I run the command listed in the README:

   opam pin add -y m17n git://github.com/whitequark/ocaml-m17n

`ocamlfind query m17n` correctly finds the installed library for `m17n`. When I clone the repo, and do `opam pin add .`, then `ocamlfind` does not find the library correctly and it doesn't appear to be built. Do you know why? Surely you must be developing locally at some point and would have run into the same issue I'm seeing, correct?

**Comment by whitequark** [comment]
You need `opam pin add m17n .`, I think

**Comment by jordwalke** [comment]
Oh, yeah I did run that command in the right way, but I just realized that I used the incorrect name `ocaml-m17n` - though I did use it consistently with `opam` and `ocamlfind`.
Thanks!

**Comment by jordwalke** [comment]
BTW: I found `m17n` to be possibly the best example of adding a new syntax extension in a way that works with `utop`, and the entire ecosystem. Do you know of any other syntax extensions that are as comprehensive, or should this repo be pointed to as the best example?

Edit: I was thinking of something like a template project that "does everything right" for creating a preprocessor level syntax extension (I understand that `-ppx` is the right way to go for more modest extensions, but there is very little documentation about going the `-pp` route).)
