### ISSUE TITLE
Could you please explain transmogrification

### ISSUE THREAD

**Issue by jordwalke** [whitequark/ocaml-m17n#2]
https://github.com/whitequark/ocaml-m17n/blob/master/src/m17n_util.ml#L70

I'm unclear as to why you needed to carry out all this magic here with an expunged top level. Is this only related to `m17n`? I tried using the standard Lexer, and I had trouble catching errors correctly without your `transmogrify` hacks, so I began to think it didn't have anything to do with the `m17n` lexer itself and it was just something you had to do to build quality error catching/reporting in a custom `utop` implementation.

**Comment by whitequark** [comment]
See https://github.com/dbuenzli/rresult/issues/5#issuecomment-77076501

**Comment by jordwalke** [comment]
So would you confirm that this is not an issue with `m17n` in particular?

**Comment by whitequark** [comment]
Sure. This is a problem related only to toplevel expunging (done by regular toplevel and utop alike).
